### ISSUE TITLE
Authentication, first iteration

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-api#18]
We need authentication. This is "easier said than done", as we need to update ALL services to propagate the authentication.

We want user logins, but for first iteration we'll stick with a single auth token that's used in frontend and backend.

Updates per repo:
- web:
  - add way to set auth token for when making requests. Easiest and most secure way would be to have a simple login field where you paste the token, and the token is saved IN MEMORY instead of in cookies or local/session storage. This is for security sake as the token does not change. Users can still store the token in their password managers so it shouldn't be that big of a hassle for the users.

  - this login page should be presented when the user opens Wharf, as you cannot fetch the list of projects without being authenticated

- api:
  - assert that the requests are authenticated in EVERY endpoint. To start with we're doing full lockdown of Wharf.

- providers:
  - no need to assert the authentication, the API deals with that; but pass the key along to the Wharf Go client so it is sent onwards to the API.

- go client:
  - this might already be implemented here, but assert that the auth is passed along in all of the endpoints.

We could do JWT-based auth, but that feels overkill for now. Just go with a basic key that acts as just a password and nothing else. The validation of the key should be a basic `request.Header.Auth == os.GetEnv("API_KEY")`

**Comment by jilleJr** [comment]
@fredx30 I assigned you as you said you were going to book some meetings to get help from other departments/projects on how to solve this properly

**Comment by fredx30** [comment]
This is started in https://github.com/iver-wharf/rfcs/pull/13
