### ISSUE TITLE
Cannot delete projects

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-api#62]
## Expected

```sh
curl -X DELETE 'https://your-wharf-instance.com/api/project/5'
>>> OK
```

And all branches and builds, and their associate build logs and build params, are deleted as well.

As it's quite the dangerous endpoint, maybe we want to add something like `?are-you-sure=true`, or is that not necessary as it's an API anyway, meant to be used by computers?

## Actual

Response given:

```json
{
  "type": "https://iver-wharf.github.io/#/prob/api/unexpected-db-read-error",
  "title": "Error writing to database.",
  "status": 502,
  "detail": "Failed deleting project with ID 5 from database.",
  "instance": "/api/project/5",
  "errors": [
    "ERROR: update or delete on table \"project\" violates foreign key constraint \"fk_branch_project\" on table \"branch\" (SQLSTATE 23503)"
  ]
}
```

You must delete all dependent rows from the other tables `branch` and `build` (and in turn the `log` and `build_param` tables as well) before you can delete the project.

As there's no endpoints to delete them you must do it via SQL commands.

**Comment by Alexamakans** [comment]
Adding a confirmation/validation check of the request is not a bad idea I think, but I'd rather see that handled in a separate issue.

I will start working on fixing this bug.

**Comment by jilleJr** [comment]
> Adding a confirmation/validation check of the request is not a bad idea I think, but I'd rather see that handled in a separate issue.
> 
> I will start working on fixing this bug, if nobody else has already.

Sounds good! I have not started working on this, and as it was unassigned I assume noone else has either.
